/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookRouteImport } from './routes/cook'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RecipeRecipeIdRouteImport } from './routes/recipe.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdRoute = RecipeRecipeIdRouteImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/discover': typeof DiscoverRoute
  '/kitchen': typeof KitchenRoute
  '/saved': typeof SavedRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/discover': typeof DiscoverRoute
  '/kitchen': typeof KitchenRoute
  '/saved': typeof SavedRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/discover': typeof DiscoverRoute
  '/kitchen': typeof KitchenRoute
  '/saved': typeof SavedRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cook' | '/discover' | '/kitchen' | '/saved' | '/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cook' | '/discover' | '/kitchen' | '/saved' | '/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/cook'
    | '/discover'
    | '/kitchen'
    | '/saved'
    | '/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookRoute: typeof CookRoute
  DiscoverRoute: typeof DiscoverRoute
  KitchenRoute: typeof KitchenRoute
  SavedRoute: typeof SavedRoute
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookRoute: CookRoute,
  DiscoverRoute: DiscoverRoute,
  KitchenRoute: KitchenRoute,
  SavedRoute: SavedRoute,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
